### ISSUE TITLE
error to train VOC2007

### ISSUE THREAD

**Issue by kaishijeng** [delftrobotics/keras-retinanet#19]
I got an error below when I run python2 examples/train_pascal.py ~/2TB/src/VOC/VOCdevkit/VOC2007

Epoch 1/50
Traceback (most recent call last):
  File "examples/train_pascal.py", line 86, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.8-py2.7.egg/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.8-py2.7.egg/keras/engine/training.py", line 2016, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.8-py2.7.egg/keras/utils/data_utils.py", line 517, in get
    raise StopIteration(e)
StopIteration: 'PascalVocIterator' object has no attribute '_get_batches_of_transformed_samples'

Any idea? My Keras is the latest code from github.

Thanks

**Comment by kaishijeng** [comment]
I use git checkout -b 2.0.8 of Keras and still got the same error.
which branch should I use?

Thanks,

**Comment by hgaiser** [comment]
That branch should be fine, I'm using it as well. You're sure you are
currently using that version?

**Comment by kaishijeng** [comment]
Yes, I tried both 2.0.8 and 2.0.7 and both failed using
sudo pip2 install keras==2.0.7
or
sudo pip2 install keras==2.0.8

Can you provide branchinfo of the Keras github you use?

Thanks,

**Comment by hgaiser** [comment]
I believe I had also done `pip install keras --user`. The `--user`
shouldn't have any effect here.

Can you try:
- Check the files changed by the commit mentioned in my previous message on
your system. See if they reflect the changes made in that commit.
- Run:
```
import keras
print(keras.__file__)
```
To verify that python is indeed finding the keras you expect it to find
(and not a cloned version for instance).

**Comment by kaishijeng** [comment]
Now I have different error below after uninstalling and reinstalling keras
2.0.8

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py",
line 568, in data_generator_task
    generator_output = next(self._generator)
  File
"/home/fc/2TB/src/keras-retinanet/keras_retinanet/preprocessing/pascal_voc.py",
line 139, in next
    image_batch, boxes_batch = random_transform_batch(image_batch,
boxes_batch, self.image_data_generator)
  File
"/home/fc/2TB/src/keras-retinanet/keras_retinanet/preprocessing/image.py",
line 34, in random_transform_batch
    x, y, w, h = cv2.boundingRect(contour)
TypeError: points is not a numpy array, neither a scalar

Traceback (most recent call last):
  File "examples/train_pascal.py", line 86, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1,
patience=10, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py",
line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py",
line 2011, in fit_generator
    generator_output = next(output_generator)
StopIteration

**Comment by hgaiser** [comment]
That's good, it seems that it is using the correct keras then. I'm not sure
if it's related, but the Pascal VOC data generator was updated yesterday to
fix an inconsistency which might cause this error. Did you pull the latest
changes?

I'll be out of office for two days so I can only help by guessing at this
point ;)

**Comment by kaishijeng** [comment]
Yes, i did git pull to checkout the latest code. But the error still
happens.

Thanks,

**Comment by hgaiser** [comment]
Ah maybe it is because you're using opencv2? I believe they slightly changed the interface of `cv2.findContours` in opencv3. Could you try installing opencv3 if this is the case?

We should make this code compatible with opencv2/opencv3, but for now this could be a solution for you.

**Comment by hgaiser** [comment]
I'm going to assume that this was the error. Either way, the original issue seems to be resolved. Please open a new issue if necessary.

**Comment by kaishijeng** [comment]
Yes, it works OK with opencv3

Thanks
