### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by kaishijeng** [delftrobotics/keras-retinanet#21]
I have trained pascal model and like to see how good of my trained model.
Do you have a demo.py which takes a pretrained model and one jpeg image as an input and output an image with detected bounded box?

Thanks,

**Comment by hgaiser** [comment]
Not a demo.py like the one in `py-faster-rcnn`, but you can look at [this](https://github.com/delftrobotics/keras-retinanet/blob/master/examples/ResNet50RetinaNet%20-%20Pascal%20VOC.ipynb) notebook for an example on how to visualize the results from Pascal VOC.

ps. if you want you can make a PR for one.

**Comment by kaishijeng** [comment]
I am not familiar with keras. Can you help me how to load a Keras-retinanet
pretrained model in Keras.
I use keras.load_model below  and got an error, unknown layer 'UpsampleLike'

import keras

from keras.models import load_model

import matplotlib.pyplot as plt
import cv2
import os
import numpy as np
import time

import tensorflow as tf

model = load_model('snapshots/resnet50_voc_final.h5')

Error:
Using TensorFlow backend.
/usr/local/lib/python2.7/dist-packages/google/protobuf/__init__.py:37:
UserWarning: Module numpy was already imported from
/usr/local/lib/python2.7/dist-packages/numpy/__init__.pyc, but
/usr/lib/python2.7/dist-packages is being added to sys.path
  __import__('pkg_resources').declare_namespace(__name__)
/usr/local/lib/python2.7/dist-packages/google/protobuf/__init__.py:37:
UserWarning: Module six was already imported from
/usr/local/lib/python2.7/dist-packages/six.pyc, but
/usr/lib/python2.7/dist-packages is being added to sys.path
  __import__('pkg_resources').declare_namespace(__name__)
Traceback (most recent call last):
  File "examples/test.py", line 12, in <module>
    model = load_model('snapshots/resnet50_voc_final.h5')
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 239,
in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 313,
in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/__init__.py",
line 54, in deserialize
    printable_module_name='layer')
  File
"/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.py", line
139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py",
line 2487, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py",
line 2473, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/__init__.py",
line 54, in deserialize
    printable_module_name='layer')
  File
"/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.py", line
133, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: UpsampleLike

**Comment by hgaiser** [comment]
You need to let keras know where some of the custom objects are, by calling `model = keras.models.load_model("model.h5", custom_objects=keras_retinanet.custom_objects)`.

However, as of writing this model loading is broken. The workaround is to create an identical model and call `models.load_weights("model.h5", by_name=True)`. Or alternatively load the model definition first and then load weights. The rest can be seen in the notebook.

**Comment by kaishijeng** [comment]
It works with models.load_weights("model.h5", by_name=True).
Now I am facing a different issue which use mode. predict with one input image. My code is below:

    print('Creating model, this may take a second...')
    model = create_model()
    model.load_weights("snapshots/resnet50_voc_final.h5", by_name=True)
    image = cv2.imread(sys.argv[1])
    image -= min(image.flatten())
    image /= max(image.flatten())
    image *= 255
    image = image.astype(np.uint8)
    start = time.time()
    predictions, detections = model.predict(image)
    print("processing time: ", time.time() - start)

    im = image.copy()
    predicted_labels = np.argmax(detections[0, :, 4:], axis=1)
    scores = np.max(detections[0, :, 4:], axis=1)

    for idx, (label, score) in enumerate(zip(predicted_labels, scores)):
         if label == 0:
            continue
         b = detections[0, idx, :4].astype(int)
         cv2.rectangle(im, (b[0], b[1]), (b[2], b[3]), (0, 255, 0), 3)
         caption = "{} {:.3f}".format(class_names[label], score)
         cv2.putText(im, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1.5, (0, 0, 0), 3)
         cv2.putText(im, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1.5, (255, 255, 255), 2)
    plt.figure(figsize=(15, 15))
    plt.axis('off')
    plt.imshow(im)
    plt.show()

But I got the following errors:

Traceback (most recent call last):
  File "./examples/demo-pascal.py", line 65, in <module>
    predictions, detections = model.predict(image)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1695, in predict
    check_batch_axis=False)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 132, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking : expected input_1 to have 4 dimensions, but got array with shape (1288, 2048, 3)

**Comment by hgaiser** [comment]
You don't preprocess your image properly. It should firstly have 4 dimension (`(batch, height, width, channels)`). In addition the imagenet mean should be subtracted and the image should be rescaled by 1/255. For an example on how to preprocess an image you can look here : https://github.com/delftrobotics/keras-retinanet/blob/master/keras_retinanet/preprocessing/coco.py#L107

Perhaps I'll add a demo.py which follows this use case, but for now you could try replicating the preprocessing steps from the data generator.

PS. It's not so much that preprocessing *has* to be done this way, but it does *have* to be consistent with what you used during training.

**Comment by kaishijeng** [comment]
Do you still have a plan to add demo.py?

Thanks,

**Comment by hgaiser** [comment]
Not really no. If you make a nice one we can add it to the repository.
