### ISSUE TITLE
load the model generated by train_pascal.py dose not work.

### ISSUE THREAD

**Issue by sevenseablue** [delftrobotics/keras-retinanet#24]
@hgaiser , hello. 

from the closed issue. i create model, load weights.
https://github.com/delftrobotics/keras-retinanet/issues/20
 
i train model with 2 methods, first is train_pascal.py, second is ResNet50RetinaNet - Pascal VOC.ipynb.
i create model, load weights,  use the predict code segments in ResNet50RetinaNet - Pascal VOC.ipynb.
the model generated by the first  method can not predict the results, nothing recognized, the second can predict results, as common.

i think the two model is same, so i use the same predict code.
is there anything wrong? please help me to figure it out.

**Comment by hgaiser** [comment]
I'm not quite sure I get what you mean. You trained two models, one using the jupyter notebook and one using the python script? Both should follow the same training scheme so they should be similar in the end, so in that sense they are "the same".

You're saying the model trained using `train_pascal.py` fails to detect objects whereas the model from the jupyter notebook works fine?

I believe the predict code from the jupyter notebook is slightly outdated, I will update that tomorrow when I have the chance. But that doesn't sound like your issue. Can you elaborate further?

**Comment by sevenseablue** [comment]
yes,  it is what i mean. i can not elaborate further.

i copy the predict code seg from ipynb to train_pascal.py, add the load_weights code line. it works fine.

finnaly, if i use py train, i use py predict. if i use ipynb train, i use ipynb predict. it will be ok. 
otherwise, switch, is will be wrong.

it seems that the model created by using the ipynb and py is different,  or the environment is different.

**Comment by hgaiser** [comment]
Can you share a minimalistic code example of your problem?

**Comment by hgaiser** [comment]
Is this problem still relevant?

**Comment by sevenseablue** [comment]
the problem exists, but it doesn't matter.
