### ISSUE TITLE
'freeze_bn' not recognized

### ISSUE THREAD

**Issue by mhwilder** [delftrobotics/keras-retinanet#31]
Hi there... thanks for putting together this repo.
I was trying to run the coco training code and ran into the following error:

Traceback (most recent call last):
  File "examples/train_coco.py", line 60, in <module>
    model = create_model(weights=args.weights)
  File "examples/train_coco.py", line 38, in create_model
    return ResNet50RetinaNet(image, num_classes=90, weights=weights)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/models/resnet.py", line 36, in ResNet50RetinaNet
  File "build/bdist.linux-x86_64/egg/keras_resnet/models/_2d.py", line 178, in ResNet50
  File "build/bdist.linux-x86_64/egg/keras_resnet/models/_2d.py", line 82, in ResNet
  File "build/bdist.linux-x86_64/egg/keras/legacy/interfaces.py", line 87, in wrapper
TypeError: __init__() got an unexpected keyword argument 'freeze_bn'

Any thoughts on what might be wrong with my setup?

Thanks.

**Comment by hgaiser** [comment]
I'm guessing you don't have the latest version (`master` even) of [`keras-resnet`](https://github.com/broadinstitute/keras-resnet) installed. I'll update the README.md with a guide on how to install `keras-retinanet`.

**Comment by mhwilder** [comment]
Thanks. When I ran the setup script, this is what was installed:

Installed /usr/local/lib/python2.7/dist-packages/keras_retinanet-0.0.1-py2.7.egg
Processing dependencies for keras-retinanet==0.0.1
Searching for keras-resnet
Reading https://pypi.python.org/simple/keras-resnet/
Downloading https://pypi.python.org/packages/30/19/a348c06440276c575a578ae41a953e81ba7a643bb548afda19fad5c89775/keras-resnet-0.0.8.tar.gz#md5=07f8e0f6462df78a4662c77f0da02f9d
Best match: keras-resnet 0.0.8
Processing keras-resnet-0.0.8.tar.gz
Writing /tmp/easy_install-EjGzMF/keras-resnet-0.0.8/setup.cfg
Running keras-resnet-0.0.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-EjGzMF/keras-resnet-0.0.8/egg-dist-tmp-bYQGtV
zip_safe flag not set; analyzing archive contents...
Moving keras_resnet-0.0.8-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding keras-resnet 0.0.8 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/keras_resnet-0.0.8-py2.7.egg

Does that look like an older version?

**Comment by jwnsu** [comment]
check closed issue for solution: https://github.com/delftrobotics/keras-retinanet/issues/16.

**Comment by hgaiser** [comment]
[This](https://github.com/delftrobotics/keras-retinanet/commit/288fe3db449fd94be809fc606c468a38b8bf749c) commit should address this issue. Feedback on this guide is welcome, I couldn't test it fully due to that `tensorflow-gpu` on pypi seems to use CUDA 8 while I have CUDA 9 installed.

If it doesn't work and you need to take extra steps, I'd be happy to hear them.

Also if this resolves your issue, please close this issue.

**Comment by mhwilder** [comment]
Thanks for the update and the quick response to this issue. I was able to get it to work by cloning keras-resnet repo and installing it (which looks to be what you suggest in the updated readme). Seems to be working now.
