### ISSUE TITLE
error to train VOC2007

### ISSUE THREAD

**Issue by jwnsu** [delftrobotics/keras-retinanet#33]
Pulled latest codes, saw following error during training (ubuntu 16.04/keras2.0.8/tensorflow 1.2):
"File "/home/ai/krn/keras_retinanet/preprocessing/pascal_voc.py", line 149, in load_image
    regression_targets         = np.append(regression_targets, np.expand_dims(labels, axis=1), axis=1)
  File "/home/dsu/tf/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 5152, in append
    return concatenate((arr, values), axis=axis)
ValueError: all the input arrays must have same number of dimensions".

Earlier, saw error: "
File "/home/ai/krn/keras_retinanet/preprocessing/pascal_voc.py", line 148, in load_image
    labels, regression_targets = anchor_targets(image, boxes_batch[0])
TypeError: anchor_targets() takes at least 3 arguments (2 given)", which was resolved by adding 3rd-parameter len(self.classes).

**Comment by hgaiser** [comment]
Thanks for reporting this issue! Seems Pascal training wasn't kept up to date. Should be fixed by commit https://github.com/delftrobotics/keras-retinanet/commit/d52ee112b4a14c6447b8b2293086bc71d18836d7 .

**Comment by jwnsu** [comment]
need to fix next 2 lines as well (simply copy from coco.py, the issues will go away.)

**Comment by hgaiser** [comment]
Thanks, I'll make those changes.
