### ISSUE TITLE
voc 2017 training error

### ISSUE THREAD

**Issue by jwnsu** [delftrobotics/keras-retinanet#34]
Thanks a lot for a few recent fixes, now training is underway. 

During training, it would stop on random itreation (it may continue for hundreds of images, then encounter the error ):
"    labels, regression_targets = anchor_targets(image, boxes_batch[0],len(self.classes))
  File "/home/ai/krn/keras_retinanet/preprocessing/anchors.py", line 29, in anchor_targets
    argmax_overlaps_inds = np.argmax(overlaps, axis=1)
  File "/home/tf/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 963, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/home/tf/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence".

Seems to be some type of batch data generation issue somewhere.

**Comment by hgaiser** [comment]
Ah seems you have an image where none of the anchors have a significant overlap with any of the ground truth bounding boxes. Could you find out for which image this error occurs? Then I can debug it better.

Regardless, processing images with no ground truth boxes or where no box has significant overlap should be fixed.

**Comment by jwnsu** [comment]
Thanks. Will scan images, training on own dataset. It's known a dozen or so images have no objects.

**Comment by jwnsu** [comment]
In fact, I propose to catch exception in pascal_voc.py's next(self) method: if there is an exception, simply go to next one. Will try this fix, if it works, I will send you changes.
