### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by wanghuok** [delftrobotics/keras-retinanet#37]
Hello,  when i run 'Run detection on example' section in "ResNet50RetinaNet - COCO 2017.ipynb", i encounter this error, what's wrong whit it?
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-f56c15ba16bb> in <module>()
----> 1 image_batch, outputs = next(test_generator)
      2 image = image_batch[0, ...].copy()
      3 image -= min(image.flatten())
      4 image /= max(image.flatten())
      5 image *= 255

/home/wh/.local/lib/python2.7/site-packages/keras_retinanet/preprocessing/coco.pyc in next(self)
    138         # lock indexing to prevent race conditions
    139         with self.lock:
--> 140             selection, _, batch_size = next(self.index_generator)
    141 
    142         assert(batch_size == 1), "Currently only batch_size=1 is allowed."

ValueError: need more than 1 value to unpack

**Comment by hgaiser** [comment]
What version of keras are you running ?
```
print(keras.__version__)
```

**Comment by wanghuok** [comment]
>>> print keras.__version__
2.0.9
python 2.7.13

**Comment by hgaiser** [comment]
You can try [this](https://github.com/delftrobotics/keras-retinanet/pull/36) branch, or install keras 2.0.8. I suspect that will help with your issue.

**Comment by wanghuok** [comment]
Thanks, when i reinstall keras 2.0.8. that error was disappeared.
if i only want to run "Run detection on example" section, whether should i run "Train on data" section first?

**Comment by hgaiser** [comment]
If you load a model in your notebook then training isn't necessary.

**Comment by wanghuok** [comment]
Yes, i load a model "resnet50_coco_best_v1.0.0.h5". 
but, when i run "Run detection on example" code, i encounter this error: "AttributeError: 'NoneType' object has no attribute 'shape'" at this line "image_batch, outputs = next(test_generator)".  it seems that it didn't find any image. but my test_generator initialized successfully. please see below:
# create a generator for testing data
test_generator = keras_retinanet.preprocessing.coco.CocoIterator(
    '/home/wh/Downloads',
    'val2017',
    test_image_data_generator,
)
it outputs :
loading annotations into memory...
Done (t=0.54s)
creating index...
index created!

**Comment by hgaiser** [comment]
What is the structure of your COCO dataset? It should be:

```
/path/to/COCO/
/path/to/COCO/annotations/
/path/to/COCO/images/train2017/
/path/to/COCO/images/val2017/
```

**Comment by wanghuok** [comment]
Yeah. it works. thank you.
