### ISSUE TITLE
deconvolution is unmatched with the output shape 

### ISSUE THREAD

**Issue by liuwei16** [delftrobotics/keras-retinanet#4]
when applying deconvolution for 9x15x256, output is 18x30x256, which is unmatched with 17x30x256 when  operarion of adding is performed.
How to figure out this issue?
Thank you very much.

**Comment by hgaiser** [comment]
I've noticed this too, so far I kept the image sizes as a factor of 2. A solution would be to use bilinear upsampling to a prespecified size, as described in the paper. I'm curious about the qualitative difference between the two actually. Instinctively I would think Deconv works better. What would you propose?

**Comment by hgaiser** [comment]
Solved by https://github.com/delftrobotics/keras-retinanet/commit/b04c4798b6bb3992c7723887bceea45c27b5d99a .

**Comment by liuwei16** [comment]
@hgaiser I donot think resizing is good enough, how about deconvolution+cropping to match the output shape?

**Comment by hgaiser** [comment]
Why do you think resizing is not good enough?

https://distill.pub/2016/deconv-checkerboard/
