### ISSUE TITLE
StopIteration: points is not a numpy array, neither a scalar

### ISSUE THREAD

**Issue by nealzGu** [delftrobotics/keras-retinanet#43]
Hi again,

I want to train on VOCpascal and get this error message. From an earlier, similar issue, it had something to do with OpenCV, but this one seems different.

Sharing experiences or ideas will be highly appreciated !!

_ _ _
.
.
Total params: 36,213,592
Trainable params: 36,107,352
Non-trainable params: 106,240
__________________________________________________________________________________________________
None
Epoch 1/50
Traceback (most recent call last):
  File "examples/train_pascal.py", line 105, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2046, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 518, in get
    raise StopIteration(e)
StopIteration: points is not a numpy array, neither a scalar

**Comment by nealzGu** [comment]
versions:
python 2.7.6
keras 2.0.9

**Comment by hgaiser** [comment]
What is your OpenCV version?

**Comment by nealzGu** [comment]
2.4.8

**Comment by hgaiser** [comment]
Could you try OpenCV 3+?

**Comment by nealzGu** [comment]
having quite some problems with this ... try to fix it tomorrow!

**Comment by hgaiser** [comment]
Alternatively, if you change the code there such that it is not using OpenCV (at the point where the error comes from) and make a PR out of it I'd be happy to merge it.

**Comment by nealzGu** [comment]
Luckily that's not necessary - it works now!

For everybody who is experiencing the same error, this worked for me:
remove existing openCV with
`sudo apt-get autoremove opencv-doc opencv-data libopencv-dev libopencv2.4-java libopencv2.4-jni python-opencv libopencv-core2.4 libopencv-gpu2.4 libopencv-ts2.4 libopencv-photo2.4 libopencv-contrib2.4 libopencv-imgproc2.4 libopencv-superres2.4 libopencv-stitching2.4 libopencv-ocl2.4 libopencv-legacy2.4 libopencv-ml2.4 libopencv-video2.4 libopencv-videostab2.4 libopencv-objdetect2.4 libopencv-calib3d2.4`

then just do:
`pip install opencv-python`

there are a lot of other complicated descriptions out there that didnt work for me, this is the simplest one and worked fine. Will close this issue, thanks again!
