### ISSUE TITLE
need more than 1 value to unpack

### ISSUE THREAD

**Issue by nealzGu** [delftrobotics/keras-retinanet#45]
Hey guys, when I run inference with ipyn (VOCpascal) I get this error:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-f56c15ba16bb> in <module>()
----> 1 image_batch, outputs = next(test_generator)
      2 image = image_batch[0, ...].copy()
      3 image -= min(image.flatten())
      4 image /= max(image.flatten())
      5 image *= 255

/usr/local/lib/python2.7/dist-packages/keras_retinanet/preprocessing/pascal_voc.pyc in next(self)
    179         # lock indexing to prevent race conditions
    180         with self.lock:
--> 181             selection, _, batch_size = next(self.index_generator)
    182 
    183         result = self._get_batches_of_transformed_samples(selection)

ValueError: need more than 1 value to unpack`

the initialization of data throws no error, actually gives no feedback at all, but I think its fine.
path should be correct, test.txt exists and contains just one line: the name of the image (without .jpg)

I saw [here](https://github.com/delftrobotics/keras-retinanet/issues/37) that someone had kind of the same error. downgrading to keras 2.0.8 throws a new error at a prior step, so I would like to avoid that. I think I have all the changes from the PR mentioned in the other issue.

Any ideas or advice or workarounds?

versions:
python 2.7.6
keras 2.0.9

**Comment by hgaiser** [comment]
It seems the usage of the `index_generator` changed since 2.0.9. I just pushed a change for this (https://github.com/delftrobotics/keras-retinanet/commit/5ee4765aa0e5743c5b624091f32a205cf9d5ef53). Can you give it a try?

**Comment by nealzGu** [comment]
yes, that was my first try as well, sadly same error :-(

**Comment by hgaiser** [comment]
For me it seems to train normally. You can try to print the output of `next(self.index_generator)`, maybe that gives us a better idea of what is going wrong.

**Comment by nealzGu** [comment]
thanks for your help.

I just realized that I had to change the script in /usr/local/... with sudo permission and that the changes I made in my cloned git repo folder didn't lead to any changes... 
Is this because of something I missed during installation?

unrelated: it is working now (at least not throwing errors). I trained outside of the ipyn and want to run inference now. If I wanna use the ipyn, I just skip the "train on data" part, right?
But don't I skip the "load pretrained weights" part in this case as well?! 
Sorry, different topic, I will close this thread directly afterwards :)

**Comment by hgaiser** [comment]
By default python will use the version from your `/usr/` directory. You can run your programs with `PYTHONPATH=/path/to/your/cloned/keras-retinanet python examples/train_pascal.py`. This will make python have a preference of using your local (non-installed) copy.



> unrelated: it is working now (at least not throwing errors). I trained outside of the ipyn and want to run inference now. If I wanna use the ipyn, I just skip the "train on data" part, right?
> But don't I skip the "load pretrained weights" part in this case as well?!
> Sorry, different topic, I will close this thread directly afterwards :)

Yeah exactly. If you change the `weights` parameter when creating the model to point to your saved model, it should use those weights. ie.:
```
model = keras_retinanet.models.ResNet50RetinaNet(image_input, num_classes=20, nms=True, weights='snapshots/resnet50_voc_best.h5')
```

**Comment by nealzGu** [comment]
ahhhh right, that thing. thanks again, everything is working fine now. you helped me a lot :-)
